export const EDIT_NAME_CARD = 'EDIT_NAME_CARD';
export const SAVE_NAME_CARD = 'SAVE_NAME_CARD';
export const CANCEL_NAME_CARD = 'CANCEL_NAME_CARD';
export const SEARCH_NAME_CARD = 'SEARCH_NAME_CARD';


export const SHOW_DETAIL_NAME_CARD = 'SHOW_DETAIL_NAME_CARD';
export const DRAWER_SECTION_SWITCH = 'DRAWER_SECTION_SWITCH';