export const EDIT_NAME_CARD = 'EDIT_NAME_CARD';
export const SAVE_NAME_CARD = 'SAVE_NAME_CARD';
export const CANCEL_NAME_CARD = 'CANCEL_NAME_CARD';
export const FILTER_NAME_CARD = 'FILTER_NAME_CARD';
export const SEARCH_NAME_CARD = 'SEARCH_NAME_CARD';